tcp: tcpclient
tcpclient: tcpserver.o
	cc tcpclient.c -o tcpclient
tcpserver.o: tcpserver.c 
	cc tcpserver.c -o tcpserver
udp: udpclient
udpclient: udpserver.o
	cc udpclient.c -o udpclient
udpserver.o: udpserver.c
	cc udpserver.c -o udpserver

